namespace OpenGraal.Server.Game.Players;

/*
bool __getLogin[propscount] =
{
	NickName,  
	SwordPowerAndImage,
    ShieldPowerAndImage,
    Gani,
    HeadImage,
    Chat,
    Colors,
	X,
    Y,
    Sprite,
    Status,
    CarrySprite,
    Level,
    HorseImage,
	CarryNpc,
    IpAddr,
    UdpPort,
    Alignment,
    AccountName,
    BodyImage,
    Rating,
    GaniAttribute1,
    GaniAttribute2,
    GaniAttribute3,
    GaniAttribute4,
    GaniAttribute5,
	GmapLevelX,
    GmapLevelY,
    Z,
    GaniAttribute6,
    GaniAttribute7,
    GaniAttribute8,
    GaniAttribute9,
    PLPROP_JOINLEAVELVL,
	StatusMessage,
    GaniAttribute10,
    GaniAttribute11,
    GaniAttribute12,
    GaniAttribute13,
    GaniAttribute14,
    GaniAttribute15,
    GaniAttribute16,
    GaniAttribute17,
    GaniAttribute18,
    GaniAttribute19,
    GaniAttribute20,
    GaniAttribute21,
    GaniAttribute22,
    GaniAttribute23,
    GaniAttribute24,
    GaniAttribute25,
    GaniAttribute26,
    GaniAttribute27,
    GaniAttribute28,
    GaniAttribute29,
    GaniAttribute30, 
    X2,
    Y2,
    Z2,
	CommunityName, 
};
 */

public enum PlayerProperty
{
    NickName = 0,
    MaxHp = 1,
    Hp = 2,
    Gralats = 3,
    Arrows = 4,
    Bombs = 5,
    GlovePower = 6,
    BombPower = 7,
    SwordPowerAndImage = 8,
    ShieldPowerAndImage = 9,
    Gani = 10,
    HeadImage = 11,
    Chat = 12,
    Colors = 13,
    Id = 14,
    X = 15,
    Y = 16,
    Sprite = 17,
    Status = 18,
    CarrySprite = 19,
    Level = 20,
    HorseImage = 21,
    HorseBushes = 22,
    EffectColors = 23,
    CarryNpc = 24,
    ApCounter = 25,
    Mp = 26,
    Kills = 27,
    Deaths = 28,
    OnlineTime = 29,
    IpAddr = 30,
    UdpPort = 31,
    Alignment = 32,
    AdditionalFlags = 33,
    AccountName = 34,
    BodyImage = 35,
    Rating = 36,
    GaniAttribute1 = 37,
    GaniAttribute2 = 38,
    GaniAttribute3 = 39,
    GaniAttribute4 = 40,
    GaniAttribute5 = 41,
    AttachNpc = 42,
    GmapLevelX = 43,
    GmapLevelY = 44,
    Z = 45,
    GaniAttribute6 = 46,
    GaniAttribute7 = 47,
    GaniAttribute8 = 48,
    GaniAttribute9 = 49,
    PLPROP_JOINLEAVELVL = 50,
    PLPROP_PCONNECTED = 51,
    Language = 52,
    StatusMessage = 53,
    GaniAttribute10 = 54,
    GaniAttribute11 = 55,
    GaniAttribute12 = 56,
    GaniAttribute13 = 57,
    GaniAttribute14 = 58,
    GaniAttribute15 = 59,
    GaniAttribute16 = 60,
    GaniAttribute17 = 61,
    GaniAttribute18 = 62,
    GaniAttribute19 = 63,
    GaniAttribute20 = 64,
    GaniAttribute21 = 65,
    GaniAttribute22 = 66,
    GaniAttribute23 = 67,
    GaniAttribute24 = 68,
    GaniAttribute25 = 69,
    GaniAttribute26 = 70,
    GaniAttribute27 = 71,
    GaniAttribute28 = 72,
    GaniAttribute29 = 73,
    GaniAttribute30 = 74,
    OsType = 75, // 2.19+
    Codepage = 76, // 2.19+
    PLPROP_UNKNOWN77 = 77,
    X2 = 78,
    Y2 = 79,
    Z2 = 80,
    PLPROP_UNKNOWN81 = 81,

    // In Graal v5, where players have the Graal######## accounts, this is their chosen account alias (community _name.)
    CommunityName = 82,
}