name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [ 'linux-x64', 'win-x64' ]
        os: [ 'Linux', 'Windows' ]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        shell: bash
        run: dotnet publish OpenGraal.Server/OpenGraal.Server.csproj -c Release -f net9.0 -r ${{ matrix.runtime }} -o ./Publish --self-contained true

      - name: Zip
        run: |
          cd ./Publish
          zip -r ../OpenGraal-${{ matrix.os }}-${{ github.ref_name }}.zip ./
          cd ..

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: OpenGraal-${{ matrix.os }}-${{ github.ref_name }}
          path: OpenGraal-${{ matrix.os }}-${{ github.ref_name }}.zip